# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_foodtypes_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useraccount', models.CharField(max_length=20, unique=True)),
                ('upassword', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('userphone', models.CharField(max_length=20)),
                ('useradderss', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
