# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='useradderss',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='userccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.userinfo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='usergoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods'),
        ),
    ]
