# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_auto_20171017_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userccount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='usergoods',
            field=models.CharField(max_length=20),
        ),
    ]
