# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_auto_20171017_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nccount', models.CharField(max_length=20)),
                ('ngoodsid', models.CharField(max_length=20)),
            ],
        ),
    ]
