# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_newcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tccount', models.CharField(max_length=20)),
                ('tgoodid', models.CharField(max_length=20)),
                ('tgoodnum', models.IntegerField()),
            ],
        ),
    ]
