# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_twocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tccount', models.CharField(max_length=20)),
                ('tgoodnum', models.IntegerField()),
                ('tgoodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
            ],
        ),
    ]
