# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_xcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='upassword',
            field=models.CharField(max_length=300),
        ),
    ]
